name: Flutter Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: "Install dependencies"
        run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build build-essential pkg-config curl file git unzip xz-utils zip libgtk-3-dev

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk

      - name: Build web app
        run: flutter build web

      - name: Build Linux app
        run: flutter build linux
      
      - name: Build AppImage unsing appimage-builder
        uses: docker://appimagecrafters/appimage-builder:0.8.5
        with:
          entrypoint: appimage-builder
          args: --recipe ./AppImageBuilder.yml --skip-test

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: |
            build/app/outputs/apk/release/
            
            build/web/
            ./*.AppImage*

  release-on-ubuntu:
    needs: build-and-release-on-ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            build/app/outputs/apk/release/*.apk
            build/web/
            ./*.AppImage*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-release-on-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Build macOS app
        run: flutter build macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: |
            build/ios/iphoneos/Runner.app
            build/macos/Build/Products/Release/Runner.app

  build-and-release-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter build windows
  release-on-macos:
    needs: build-and-release-on-macos
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            build/windows/runner/Release/*.exe

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-on-windows:
    needs: build-and-release-on-windows
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            build/windows/runner/Release/*.exe

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
